### ISSUE TITLE
Проблемка со студиями

### ISSUE THREAD

**Issue by ghost** [ilyamikheevcoder/scratch-api-unofficial-russian-docs#1]
Здесь написано следующее:
```
"visibility": /* Видимость студии...? Нет точных данных, зачем это нужно, ибо студии всегда видны. Должно быть всегда равно "visible". */
```
Но почему-то в моём случае это не так... Студии из API "Исследуй" отмечены как "notvisible"!

**Comment by ilyamikcoder** [comment]
У студий обновился API - могло поменятся. Я посмотрю подробнее, когда продолжу работу над доками (если продолжу)
